### ISSUE TITLE
Got stuck in https://id.fedoraproject.org/ page after login with FAS

### ISSUE THREAD

**Issue by rtnpro** [fedora-infra/flock-registration#23] opened 2014-03-13 21:12 UTC
I got stuck in https://id.fedoraproject.org/ page after I logged in with FAS at https://flock-lmacken.rhcloud.com/.

**Comment by lmacken** [comment] 2014-03-13 23:07
Are you able to reproduce this issue? Or was just a one-time glitch?

I think that redirect is coming from FedOAuth, so I'll \cc @puiterwijk

**Comment by puiterwijk** [comment] 2014-03-13 23:14
This might be caused by FedOAuth/FedOAuth#53.
As I just wrote there, I hope to have a permanent fix in very soon (hopefully today).

A temporary workaround is by trying it again, the second time it works.
(Or by using firefox, as so far the bug has only been re-reported on Google Chrome).

**Comment by lmacken** [comment] 2014-03-14 00:26
Thanks, Patrick.

Closing this issue, since it's filed upstream.

**Closed as completed by lmacken** 2014-03-14 00:26 UTC
